[package]
name = "g4-interrupts"
version = "0.1.0"
edition = "2021"

[dependencies]
proto-hal = { path = "/Users/adinack/Projects/proto-hal/proto-hal" }
cortex-m-rt = { version = "0.7.3", features = ["device"] }
