use proto_hal_build::ir::{
    access::Access,
    structures::{
        field::{Field, Numericity},
        variant::Variant,
    },
};

pub fn generate() -> Field {
    Field::new(
        "dmareq",
        0,
        7,
        Access::read_write(Numericity::enumerated([
            Variant::new("None", 0),
            Variant::new("G0", 1),
            Variant::new("G1", 2),
            Variant::new("G2", 3),
            Variant::new("G3", 4),
            Variant::new("Adc1", 5),
            Variant::new("Dac1Ch1", 6),
            Variant::new("Dac1Ch2", 7),
            Variant::new("Tim6Up", 8),
            Variant::new("Tim7Up", 9),
            Variant::new("Spi1Rx", 10),
            Variant::new("Spi1Tx", 11),
            Variant::new("Spi2Rx", 12),
            Variant::new("Spi2Tx", 13),
            Variant::new("Spi3Rx", 14),
            Variant::new("Spi3Tx", 15),
            Variant::new("I2c1Rx", 16),
            Variant::new("I2c1Tx", 17),
            Variant::new("I2c2Rx", 18),
            Variant::new("I2c2Tx", 19),
            Variant::new("I2c3Rx", 20),
            Variant::new("I2c3Tx", 21),
            Variant::new("I2c4Rx", 22),
            Variant::new("I2c4Tx", 23),
            Variant::new("Usart1Rx", 24),
            Variant::new("Usart1Tx", 25),
            Variant::new("Usart2Rx", 26),
            Variant::new("Usart2Tx", 27),
            Variant::new("Usart3Rx", 28),
            Variant::new("Usart3Tx", 29),
            Variant::new("Uart4Rx", 30),
            Variant::new("Uart4Tx", 31),
            Variant::new("Uart5Rx", 32),
            Variant::new("Uart5Tx", 33),
            Variant::new("Lpuart1Rx", 34),
            Variant::new("Lpuart1Tx", 35),
            Variant::new("Adc2", 36),
            Variant::new("Adc3", 37),
            Variant::new("Adc4", 38),
            Variant::new("Adc5", 39),
            Variant::new("QuadSpi", 40),
            Variant::new("Dac2Ch1", 41),
            Variant::new("Tim1Ch1", 42),
            Variant::new("Tim1Ch2", 43),
            Variant::new("Tim1Ch3", 44),
            Variant::new("Tim1Ch4", 45),
            Variant::new("Tim1Up", 46),
            Variant::new("Tim1Trig", 47),
            Variant::new("Tim1Com", 48),
            Variant::new("Tim8Ch1", 49),
            Variant::new("Tim8Ch2", 50),
            Variant::new("Tim8Ch3", 51),
            Variant::new("Tim8Ch4", 52),
            Variant::new("Tim8Up", 53),
            Variant::new("Tim8Trig", 54),
            Variant::new("Tim8Com", 55),
            Variant::new("Tim2Ch1", 56),
            Variant::new("Tim2Ch2", 57),
            Variant::new("Tim2Ch3", 58),
            Variant::new("Tim2Ch4", 59),
            Variant::new("Tim2Up", 60),
            Variant::new("Tim3Ch1", 61),
            Variant::new("Tim3Ch2", 62),
            Variant::new("Tim3Ch3", 63),
            Variant::new("Tim3Ch4", 64),
            Variant::new("Tim3Up", 65),
            Variant::new("Tim3Trig", 66),
            Variant::new("Tim4Ch1", 67),
            Variant::new("Tim4Ch2", 68),
            Variant::new("Tim4Ch3", 69),
            Variant::new("Tim4Ch4", 70),
            Variant::new("Tim4Up", 71),
            Variant::new("Tim5Ch1", 72),
            Variant::new("Tim5Ch2", 73),
            Variant::new("Tim5Ch3", 74),
            Variant::new("Tim5Ch4", 75),
            Variant::new("Tim5Up", 76),
            Variant::new("Tim5Trig", 77),
            Variant::new("Tim15Ch1", 78),
            Variant::new("Tim15Up", 79),
            Variant::new("Tim15Trig", 80),
            Variant::new("Tim15Com", 81),
            Variant::new("Tim16Ch1", 82),
            Variant::new("Tim16Up", 83),
            Variant::new("Tim17Ch1", 84),
            Variant::new("Tim17Up", 85),
            Variant::new("Tim20Ch1", 86),
            Variant::new("Tim20Ch2", 87),
            Variant::new("Tim20Ch3", 88),
            Variant::new("Tim20Ch4", 89),
            Variant::new("Tim20Up", 90),
            Variant::new("AesIn", 91),
            Variant::new("AesOut", 92),
            Variant::new("Tim20Trig", 93),
            Variant::new("Tim20Com", 94),
            Variant::new("HrtimMaster", 95),
            Variant::new("HrtimTimA", 96),
            Variant::new("HrtimTimB", 97),
            Variant::new("HrtimTimC", 98),
            Variant::new("HrtimTimD", 99),
            Variant::new("HrtimTimE", 100),
            Variant::new("HrtimTimF", 101),
            Variant::new("Dac3Ch1", 102),
            Variant::new("Dac3Ch2", 103),
            Variant::new("Dac4Ch1", 104),
            Variant::new("Dac4Ch2", 105),
            Variant::new("Spi4Rx", 106),
            Variant::new("Spi4Tx", 107),
            Variant::new("Sai1A", 108),
            Variant::new("Sai1B", 109),
            Variant::new("FmacRead", 110),
            Variant::new("FmacWrite", 111),
            Variant::new("CordicRead", 112),
            Variant::new("CordicWrite", 113),
            Variant::new("Ucpd1Rx", 114),
            Variant::new("Ucpd1Tx", 115),
        ])),
    )
    .docs(["DMA request"])
}
