[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip STM32G474RE'

rustflags = [
    "-C",
    "linker=flip-link",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabi"
